// filepath: src/features/properties/inventoryConfig/itemCatalogBanosYcocina.ts
// Baños (3 variantes) + Cocina. Basado en PDF Afiansa INVENTARIO EN BLANCO.
import type { ItemDef } from "./types";

export const ITEM_CATALOG_BANOS_Y_COCINA: Record<string, ItemDef[]> = {
  /** BAÑO (Principal, Auxiliar, Alcoba, Emergencia): completo */
  bano: [
    { id: "puerta", label: "Puerta" },
    { id: "marco_puerta", label: "Marco Puerta" },
    { id: "cerradura", label: "Cerradura" },
    { id: "ventanas", label: "Ventanas" },
    { id: "vidrios", label: "Vidrios" },
    { id: "lavamanos", label: "Lavamanos" },
    { id: "sanitario", label: "Sanitario" },
    { id: "griferia_sanitario", label: "Grifería Sanitario" },
    { id: "toallero", label: "Toallero" },
    { id: "jabonera", label: "Jabonera" },
    { id: "cepillero", label: "Cepillero" },
    { id: "ducha", label: "Ducha" },
    { id: "griferia_ducha", label: "Grifería Ducha" },
    { id: "espejos", label: "Espejos" },
    { id: "gabinetes", label: "Gabinetes" },
    { id: "divisiones", label: "Divisiones" },
    { id: "pisos", label: "Pisos" },
    { id: "paredes", label: "Paredes" },
    { id: "tomas", label: "Tomas" },
    { id: "interruptores", label: "Interruptores" },
    { id: "plafones", label: "Plafones" },
    { id: "apliques", label: "Apliques" },
    { id: "tina", label: "Tina" },
    { id: "rejillas", label: "Rejillas" },
  ],

  /** BAÑO AUXILIAR / Baño pequeño: mismo set (PDF lo lista igual) */
  bano_auxiliar: [
    { id: "puerta", label: "Puerta" },
    { id: "marco_puerta", label: "Marco Puerta" },
    { id: "cerradura", label: "Cerradura" },
    { id: "ventanas", label: "Ventanas" },
    { id: "vidrios", label: "Vidrios" },
    { id: "lavamanos", label: "Lavamanos" },
    { id: "sanitario", label: "Sanitario" },
    { id: "griferia_sanitario", label: "Grifería Sanitario" },
    { id: "toallero", label: "Toallero" },
    { id: "jabonera", label: "Jabonera" },
    { id: "cepillero", label: "Cepillero" },
    { id: "ducha", label: "Ducha" },
    { id: "griferia_ducha", label: "Grifería Ducha" },
    { id: "espejos", label: "Espejos" },
    { id: "gabinetes", label: "Gabinetes" },
    { id: "divisiones", label: "Divisiones" },
    { id: "pisos", label: "Pisos" },
    { id: "paredes", label: "Paredes" },
    { id: "tomas", label: "Tomas" },
    { id: "interruptores", label: "Interruptores" },
    { id: "plafones", label: "Plafones" },
    { id: "apliques", label: "Apliques" },
    { id: "tina", label: "Tina" },
    { id: "rejillas", label: "Rejillas" },
  ],

  /** BAÑO SOCIAL: reducido (sin tina, sin gabinetes grandes) */
  bano_social: [
    { id: "puerta", label: "Puerta" },
    { id: "marco_puerta", label: "Marco Puerta" },
    { id: "cerradura", label: "Cerradura" },
    { id: "ventanas", label: "Ventanas" },
    { id: "vidrios", label: "Vidrios" },
    { id: "lavamanos", label: "Lavamanos" },
    { id: "sanitario", label: "Sanitario" },
    { id: "griferia_sanitario", label: "Grifería Sanitario" },
    { id: "toallero", label: "Toallero" },
    { id: "jabonera", label: "Jabonera" },
    { id: "espejos", label: "Espejos" },
    { id: "pisos", label: "Pisos" },
    { id: "paredes", label: "Paredes" },
    { id: "tomas", label: "Tomas" },
    { id: "interruptores", label: "Interruptores" },
    { id: "plafones", label: "Plafones" },
    { id: "apliques", label: "Apliques" },
  ],

  /** COCINA: items planos + sub-items de muebles aplanados */
  cocina: [
    { id: "puerta", label: "Puerta" },
    { id: "marco_puerta", label: "Marco Puerta" },
    { id: "ventanas", label: "Ventanas" },
    { id: "vidrios", label: "Vidrios" },
    { id: "pisos", label: "Pisos" },
    { id: "paredes", label: "Paredes" },
    { id: "techos", label: "Techos" },
    { id: "tomas", label: "Tomas" },
    { id: "interruptores", label: "Interruptores" },
    { id: "plafones", label: "Plafones" },
    { id: "apliques", label: "Apliques" },
    { id: "lavaplatos", label: "Lavaplatos" },
    { id: "griferia", label: "Grifería" },
    { id: "estufa_asador", label: "Estufa y Asador" },
    { id: "horno", label: "Horno" },
    { id: "campana_extractora", label: "Campana Extractora" },
    { id: "mueble_inf_entrepanos", label: "Mueble Inferior — Entrepaños" },
    { id: "mueble_inf_cajones", label: "Mueble Inferior — Cajones" },
    { id: "mueble_inf_puertas", label: "Mueble Inferior — Puertas" },
    { id: "mueble_sup_entrepanos", label: "Mueble Superior — Entrepaños" },
    { id: "mueble_sup_cajones", label: "Mueble Superior — Cajones" },
    { id: "mueble_sup_puertas", label: "Mueble Superior — Puertas" },
    { id: "calentador", label: "Calentador" },
    { id: "plafones_lamparas", label: "Plafones / Lámparas" },
  ],
};
