// filepath: src/features/properties/inventoryConfig/materialCatalogMueblesYOtros.ts
// Muebles / decoración / iluminación + misceláneos (comercial).

export const MATERIAL_CATALOG_MUEBLES_Y_OTROS: Record<string, string[]> = {
  // ── Closets ──
  closet_puertas: ["Madera", "MDF", "Corredizas", "Abatibles", "PVC"],
  closet_entrepanos: ["Madera", "MDF", "Metalicos", "Vidrio"],
  closet_cajones: ["Madera", "MDF", "Metalicos", "Con rieles telescópicos"],

  // ── Muebles / decoración ──
  cortineros: ["Madera", "Metalicos", "PVC", "Aluminio", "Sin cortinero"],
  plafones: ["Drywall", "Madera", "PVC", "Yeso", "Fibra mineral"],
  plafones_lamparas: ["Drywall", "Madwall", "Madera", "PVC"],
  lamparas: [
    "LED",
    "Incandescente",
    "Fluorescente",
    "Halógena",
    "Solar",
    "Smart",
  ],
  apliques: ["Metalicos", "Cristal", "Cerámica", "LED", "Smart"],
  rosetas: ["Metalicas", "Plásticas", "Madera", "Decorativas"],
  interruptores: ["Simple", "Doble", "Triple", "Conmutado", "Smart", "Dimmer"],
  tomas: ["110V simple", "110V doble", "220V", "GFCI", "USB", "Smart"],
  cable_datos: ["Cat 5e", "Cat 6", "Cat 6A", "Fibra óptica", "Coaxial"],
  divisiones: ["Drywall", "Vidrio templado", "Madera", "Metalicas", "PVC"],
  chimenea: [
    "A leña",
    "A gas",
    "Eléctrica",
    "Decorativa (sin uso)",
    "No aplica",
  ],
  guarda_escobas: ["Madera", "Metalico", "PVC", "Empotrado en pared"],

  // ── Otros / genérico ──
  pintura: ["Vinílica", "Acrílica", "Esmalte", "Látex", "Antihumedad"],
  puertas_cortinas_metalicas: ["Metálicas", "Acero", "Aluminio", "Enrollables"],
  puerta_cortina: ["Metálica enrollable", "Acero", "Aluminio", "PVC"],
  senalizacion: ["Pintura", "Letrero luminoso", "Plástico", "Reflectiva"],
  muro: ["Concreto", "Ladrillo", "Bloque", "Mampostería", "Yeso", "Drywall"],
  vegetacion: [
    "Césped",
    "Plantas ornamentales",
    "Árboles",
    "Arbustos",
    "Sin vegetación",
  ],
  riego: ["Aspersión", "Goteo", "Manguera", "Automático", "No tiene"],
  mueble: ["Madera", "MDF", "Metalico", "Tela", "Cuero", "Mixto"],
  mostrador: [
    "Madera",
    "Mármol",
    "Granito",
    "Cuarzo",
    "Acero inoxidable",
    "Melamina",
  ],
  sillas: ["Madera", "Metalicas", "Plástico", "Tapizadas", "Cuero"],
  escritorio: ["Madera", "MDF", "Metalico", "Vidrio templado"],
  silla: ["Madera", "Metalica", "Tapizada", "Cuero", "Malla ergonómica"],
  archivador: ["Metalico", "Madera", "MDF"],
  internet: ["Fibra óptica", "Cable coaxial", "DSL", "Inalámbrico", "No tiene"],
  meson: [
    "Granito",
    "Cuarzo",
    "Mármol",
    "Acero inoxidable",
    "Concreto pulido",
    "Melamina",
  ],
  electrodomesticos: [
    "Nevera",
    "Microondas",
    "Horno",
    "Lavavajillas",
    "Licuadora",
    "Cafetera",
  ],
  estanteria: ["Metalica", "Madera", "MDF", "PVC", "Mixta"],
  piso_epoxido: ["Epóxico", "Concreto pulido", "Hormigón"],
  puertas_cortinas: ["Metálicas", "Enrollables", "Seccionales", "Rápidas"],
  cortinas: ["Metálicas", "PVC", "Lona", "Cristal"],
  capacidad_carga: ["5 T", "10 T", "20 T", "30 T", "50 T"],
  senalizacion_carga: [
    "Pintura de piso",
    "Letrero",
    "Cinta",
    "Marcación visible",
  ],
  vitrina: ["Vidrio templado", "Cristal", "Acrílico"],
  marco: ["Aluminio", "Madera", "Metalico", "PVC"],
  escalera_acceso: ["Metalica", "Madera", "Concreto", "Caracol"],
  baranda_seguridad: ["Metalica", "Acero inoxidable", "Aluminio", "PVC"],
  archivador_documentos: ["Metalico", "Madera", "Ignífugo"],
};
